version: '2.0'
services:
    mysql-app:
        image: mysql:8.0.30
        container_name: mysql
        restart: unless-stopped
        tty: 'true'
        ports:
            - "3307:3306"
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: user
            MYSQL_ROOT_PASSWORD: user
            MYSQL_DATABASE: listaApp
            MYSQL_INITDB_SKIP_TZINFO: 'true'
        networks:
            - app-network
        volumes:
            - ./database:/var/lib/mysql
    imuniza_db:
        build: ./
        container_name: app
        command: sh -c "flask --debug run --host=0.0.0.0 --port=8000"
        restart: unless-stopped
        tty: true
        working_dir: /app/
        environment:
            - DB_HOST=mysql-app
            - DB_PORT=3306
            - DB_USERNAME=user
            - DB_PASSWORD=user
            - DB_DATABASE=listaApp
        depends_on:
            - mysql-app
        ports:
            - "8000:8000"
        expose:
            - "8000"
        volumes:
            - ./:/app/
        networks:
            - app-network
networks:
    app-network:
        driver: bridge