version: '2.0'
services:
    mysql-app:
        image: mysql:8.0.30
        container_name: mysql
        restart: unless-stopped
        tty: false
        ports:
            - "3307:3306"
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: user
            MYSQL_ROOT_PASSWORD: user
            MYSQL_DATABASE: listaApp
            MYSQL_INITDB_SKIP_TZINFO: true
        networks:
            - app-network
        volumes:
            - ./database:/var/lib/mysql
    tarefas-app:
        build: ./
        container_name: tarefas-app
        command: sh -c "export DEV_DATABASE_URL=mysql+pymysql://root:user@mysql:3306/listaApp && flask --debug --app=app.py run --host=0.0.0.0 --port=8000"
        restart: unless-stopped
        tty: true
        working_dir: /app/
        depends_on:
            - mysql-app
        ports:
            - "8000:8000"
        expose:
            - "8000"
        volumes:
            - ./:/app/
        networks:
            - app-network
networks:
    app-network:
        driver: bridge
